name: Model Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest numpy
    
    - name: Verify files
      run: |
        echo "Working directory:"
        pwd
        echo "\nFiles in directory:"
        ls -la
        echo "\nContent of mnist_model.py:"
        cat mnist_model.py
        echo "\nContent of test_model.py:"
        cat test_model.py
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        CUBLAS_WORKSPACE_CONFIG: :4096:8
        PYTHONHASHSEED: 42
      run: |
        python -c "import torch; torch.manual_seed(42); torch.backends.cudnn.deterministic=True; torch.backends.cudnn.benchmark=False"
        python -m pytest -v test_model.py